source "https://rubygems.org"

gem 'rake', '~> 12.3'
gem 'require_all'
gem 'httparty'
gem 'mechanize'
gem  'rails'
gem  'pry'



group :test do
  gem "rspec"
end

group :development do
  gem 'guard-rspec', require: false
end